server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /app
spring:
  redis:
    cluster:
      nodes:
      - redis.node0.foxconn.com:6379
      - redis.node1.foxconn.com:6380
      - redis.node2.foxconn.com:6381
      - redis.node3.foxconn.com:6389
      - redis.node4.foxconn.com:6390
      - redis.node5.foxconn.com:6391
      max-redirects: 5
    lettuce:
      pool:
        max-active: 3000
        max-idle: 3000
        min-idle: 5
        max-wait: -1   